# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76363ce25d41dc45dbb0b3ca2171dca10ebcd07113bd11f3d529bab615593f157ea26a21cfdcbf2c02fd424f7d8cbf4b3a1924ed63f5af487d2cd22c5e288c57

test:
  secret_key_base: 42bed16db32689728330b588800906ec80706f85d484bf7c67744eeeb30e8a42862229ea616eb9bd1864d684023b028e6a434ba77b65567535e56febeb4c5fb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
